ERROR - 2022-11-27 23:51:36 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('122.155.166.63', 'intern', 'TVIw3yZchDLH', 'influencer', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\app\Controllers\influencer_controller.php(17): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\app\Controllers\influencer_controller.php(17): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,...')
#3 C:\xampp\htdocs\ci4\system\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
#4 C:\xampp\htdocs\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-27 23:51:36 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\influencer_controller.php(17): CodeIgniter\Database\BaseConnection->query('SELECT rawdata,follower FROM influencer_stat_post_recent WHERE network = \'twitter\' AND influencer_id = \'11081\'
        ORDER BY create_date DESC
        LIMIT 0,1')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\influencer_controller->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\influencer_controller))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
